name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Publish
        env:
          MVN_REPOSITORY: https://maven.pkg.github.com/${{ env.GITHUB_REPOSITORY }}
          MVN_USERNAME: ${{ env.GITHUB_REPOSITORY_OWNER }}
          MVN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --no-configuration-cache publish
