name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Test
        run: ./gradlew --no-daemon --no-configuration-cache test

      - name: Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          check_name: 'report'
          report_paths: '**/build/test-results/*/TEST-*.xml'
